-- CreateTable
CREATE TABLE "CLIENTES" (
    "ID_CLIENTE" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "APELLIDO" TEXT NOT NULL,
    "TELEFONO" INTEGER NOT NULL,
    "CEDULA" INTEGER NOT NULL,

    CONSTRAINT "CLIENTES_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "SERVICIOS" (
    "ID_SERVICIO" SERIAL NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,

    CONSTRAINT "SERVICIOS_pkey" PRIMARY KEY ("ID_SERVICIO")
);

-- CreateTable
CREATE TABLE "ESTADOS" (
    "ID_ESTADO" SERIAL NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,

    CONSTRAINT "ESTADOS_pkey" PRIMARY KEY ("ID_ESTADO")
);

-- CreateTable
CREATE TABLE "EMPLEADOS" (
    "ID_EMPLEADO" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "APELLIDO" TEXT NOT NULL,
    "CARGO" TEXT NOT NULL,
    "CEDULA" INTEGER NOT NULL,

    CONSTRAINT "EMPLEADOS_pkey" PRIMARY KEY ("ID_EMPLEADO")
);

-- CreateTable
CREATE TABLE "EMPLEADOS_SERVICIOS" (
    "ID_EMPLEADO_SERVICIO" SERIAL NOT NULL,
    "ID_EMPLEADO" INTEGER NOT NULL,
    "ID_SERVICIO" INTEGER NOT NULL,

    CONSTRAINT "EMPLEADOS_SERVICIOS_pkey" PRIMARY KEY ("ID_EMPLEADO_SERVICIO")
);

-- CreateTable
CREATE TABLE "TURNOS" (
    "ID_TURNO" SERIAL NOT NULL,
    "ID_CLIENTE" INTEGER NOT NULL,
    "ID_EMPLEADO" INTEGER NOT NULL,
    "ID_SERVICIO" INTEGER NOT NULL,
    "ID_ESTADO" INTEGER NOT NULL,
    "FECHA" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TURNOS_pkey" PRIMARY KEY ("ID_TURNO")
);

-- CreateIndex
CREATE UNIQUE INDEX "CLIENTES_CEDULA_key" ON "CLIENTES"("CEDULA");

-- CreateIndex
CREATE UNIQUE INDEX "EMPLEADOS_CEDULA_key" ON "EMPLEADOS"("CEDULA");

-- AddForeignKey
ALTER TABLE "EMPLEADOS_SERVICIOS" ADD CONSTRAINT "EMPLEADOS_SERVICIOS_ID_EMPLEADO_fkey" FOREIGN KEY ("ID_EMPLEADO") REFERENCES "EMPLEADOS"("ID_EMPLEADO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLEADOS_SERVICIOS" ADD CONSTRAINT "EMPLEADOS_SERVICIOS_ID_SERVICIO_fkey" FOREIGN KEY ("ID_SERVICIO") REFERENCES "SERVICIOS"("ID_SERVICIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TURNOS" ADD CONSTRAINT "TURNOS_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TURNOS" ADD CONSTRAINT "TURNOS_ID_EMPLEADO_fkey" FOREIGN KEY ("ID_EMPLEADO") REFERENCES "EMPLEADOS"("ID_EMPLEADO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TURNOS" ADD CONSTRAINT "TURNOS_ID_SERVICIO_fkey" FOREIGN KEY ("ID_SERVICIO") REFERENCES "SERVICIOS"("ID_SERVICIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TURNOS" ADD CONSTRAINT "TURNOS_ID_ESTADO_fkey" FOREIGN KEY ("ID_ESTADO") REFERENCES "ESTADOS"("ID_ESTADO") ON DELETE RESTRICT ON UPDATE CASCADE;
